Relucture de `routing.md`
vuejs-fr/nuxt pull request #11
Opened 2017-09-15 13:49 UTC by Haeresis

C'est parti !

2017-09-16 05:54 UTC, Kocal approved these changes

2017-09-16 06:58 UTC, forresst requested changes
Quelques erreurs

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +génère automatiquement :
générera

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +Pour définir une route dynmaique à l'aide d'un paramètre, vous devez définir un fichier `.vue` OU un répertoire **préfixé par un souligner (`_`)**.
dynmaique => dynamique

souligner => souligné

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +génère automatiquement :
générera

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +Comme vous pouvez le voir, la route nommée `users-id` contient le chemin `:id?` ce qui le rend optionnel; si vous voulez le rendre obligatoire, créez un fichier `index.vue` dans le dossier `users/_id
ce qui le rend optionnel;
> pourquoi la virgule a été remplacé en point virgule ?

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +Nuxt.js vous permets de créer des routes imbriquées en utilisant les routes enfants de vue-router.
permets => permet

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +va automatiquement génèrer :
générera automatiquement :

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +va automatiquement génèrer :
générera automatiquement :

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +Un middleware peut être asynchrone, retourner une `Promise` ou utiliser une fonction de rappel en seconde argument :
seconde => second

2017-09-16 06:58 UTC, forresst commented on en/guide/routing.md
> +Le middleware sont exécuté en série dans l'ordre suivant :
sont => sera

2017-09-16 08:59 UTC, Haeresis commented on en/guide/routing.md
> +Comme vous pouvez le voir, la route nommée `users-id` contient le chemin `:id?` ce qui le rend optionnel; si vous voulez le rendre obligatoire, créez un fichier `index.vue` dans le dossier `users/_id
Je vais le remplacer par un . Surement parceque en français deux idée différente font l'objet de deux phrase mais comme là il y avait une virgule !

2017-09-16 09:02 UTC, Haeresis commented
C'est dans la boîte @forresst ! Si c'est bon pour toi !

2017-09-16 10:16 UTC, rspt requested changes

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +description: Nuxt.js utilise le système de fichiers pour générer les routes de votre applications web, c'est aussi simple qu'en PHP de créer des routes.
"application" sans 's'

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +description: Nuxt.js utilise le système de fichiers pour générer les routes de votre applications web, c'est aussi simple qu'en PHP de créer des routes.
J'ai également un peu de peine avec le "c'est aussi simple que" pour deux raisons:

- Ça peut être décourageant pour des gens qui débutent, surtout s’ils n'y arrivent pas et que la doc leur dit que c'est facile
- Pour ceux qui n'ont jamais fait de PHP, la comparaison est inutile.

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +générera automatiquement :
génèrera

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +générera automatiquement :
génèrera

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +générera automatiquement :
génèrera

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +générera automatiquement :
génèrera

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +Nuxt.js utilise le composant [`<transition>`](http://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components) afin de vous permettre de créer des transitions / animations épousto
Je trouve qu'"époustouflant" est de trop.

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +puis, nous utilions la propriété transition pour définir le nom de la classe à utiliser pour cette transition de page :
"utilisons"; il manque le 's' au milieu du premier verbe

2017-09-16 10:16 UTC, rspt commented on en/guide/routing.md
> +Puis, dans `nuxt.config.js`, pour une mise en page ou une page, utilisez le mot clef `middleware` :
En graphie rectifiée: "mot-clé"

2017-09-16 10:26 UTC, Haeresis commented on en/guide/routing.md
> +description: Nuxt.js utilise le système de fichiers pour générer les routes de votre applications web, c'est aussi simple qu'en PHP de créer des routes.
Je suis plutôt d'accord avec toi. Tu peux faire cette remarque ici ? https://github.com/nuxt/docs/pull/235 ou p-e ouvrir une issue à ce sujet ?

2017-09-16 10:26 UTC, Haeresis commented on en/guide/routing.md
> +Nuxt.js utilise le composant [`<transition>`](http://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components) afin de vous permettre de créer des transitions / animations épousto
Que pense tu de « afin de vous permettre de créer de superbes transitions / animations entre vos routes. »

2017-09-16 10:26 UTC, Haeresis commented
Merci pour tes retours @rspt ! C'est dans la boîte !

2017-09-16 10:47 UTC, rspt commented on en/guide/routing.md
> +description: Nuxt.js utilise le système de fichiers pour générer les routes de votre applications web, c'est aussi simple qu'en PHP de créer des routes.
Oui je vais faire la remarque ici et on modifiera en fonction de la discussion :)

2017-09-16 10:47 UTC, rspt approved these changes

2017-09-16 10:57 UTC, Haeresis commented
Si c'est bon pour toi @forresst, on merge !

2017-09-16 11:59 UTC, forresst approved these changes

2017-09-16 12:12 UTC, merged

2017-09-25 14:24 UTC, rspt commented on en/guide/routing.md
> +description: Nuxt.js utilise le système de fichiers pour générer les routes de votre applications web, c'est aussi simple qu'en PHP de créer des routes.
@Haeresis: j'ai fait une PR sur le repo de base anglais: https://github.com/nuxt/docs/pull/257