Relecture de `views.md`
vuejs-fr/nuxt pull request #12
Opened 2017-09-16 13:26 UTC by Haeresis

Un nouveau morceau ;)

2017-09-16 13:36 UTC, rspt requested changes

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +Cette mise en page est spéciale car vous ne devez pas inclure `<nuxt />` dans son modèle. Vous devez voir cette mise en page en tant que composant affiché lorsqu'une erreur se produit (404, 500, etc.
"est spéciale, car"

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +Exemple d'une page d'erreur personalisée à l'aide de `layouts/error.vue`:
personnalisée

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +  layout: 'blog' // vous pouvez définir une mise en page personalisée pour la page d'erreur
personnalisée

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +### Mise en page personalisée
personnalisée

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +Puis dans `pages/posts.vue`, vous pouvez spécifier à Nuxt.js d'utiliser votre mise en page personalisée :
personnalisée

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +### Balises meta personalisées pour une page
personnalisées

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +    // appellé avant le chargement du composant
appelé

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +    // appellé avant le chargement du composant
Est-ce qu'on capitalise la phrase? Comme dans les autres commentaires?

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +| layout | Défini une mise en page existantes dans le répertoire `layouts`, voir [la partie pages de l'API sur `layout`](/api/pages-layout). |
"existante"

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +| validate | Fonction de validation pour les [routes dynamique](/guide/routing#routes-dynamiques). |
"[routes dynamiques]"

2017-09-16 13:36 UTC, rspt commented on en/guide/views.md
> +  attribute: 'data-n-head', // l'attribut que vue-meta ajoute aux balises observés
"observées"

2017-09-16 14:08 UTC, rspt commented on en/guide/views.md
> +Cette mise en page est spéciale car vous ne devez pas inclure `<nuxt />` dans son modèle. Vous devez voir cette mise en page en tant que composant affiché lorsqu'une erreur se produit (404, 500, etc.
@Haeresis as-tu manqué celui-ci?

2017-09-16 14:10 UTC, Haeresis commented on en/guide/views.md
> +Cette mise en page est spéciale car vous ne devez pas inclure `<nuxt />` dans son modèle. Vous devez voir cette mise en page en tant que composant affiché lorsqu'une erreur se produit (404, 500, etc.
Je sais pourquoi tu as ajouté une virgule :) C'est pour indiquer un rythme de lecture. C'est aussi comme ça que je le lirais !

Pour ma part, je n'aime généralement pas utilisé la ponctuation pour imposer un rythme de lecture, je préfère laisser le lecteur décider. La phrase étant courte ici, et l'original n'insistant pas sur la chose, je préfère ne pas en mettre.

« Lorsque les propositions coordonnées par car sont très brèves, on peut omettre la virgule. » http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3447

Bon pour toi @rspt ?

2017-09-16 14:11 UTC, Haeresis commented
Merci pour ta revue @rspt ! C'est pris en compte (je suis un peu faché avec « personnalisé » on dirait XD

2017-09-17 13:40 UTC, rspt commented on en/guide/views.md
> +Cette mise en page est spéciale car vous ne devez pas inclure `<nuxt />` dans son modèle. Vous devez voir cette mise en page en tant que composant affiché lorsqu'une erreur se produit (404, 500, etc.
Ça me convient :)

2017-09-17 13:40 UTC, rspt approved these changes

2017-09-17 13:41 UTC, rspt commented
> Merci pour ta revue @rspt ! C'est pris en compte (je suis un peu faché avec « personnalisé » on dirait XD

Ahahaha, au moins c'était partout la même chose!

2017-09-17 17:08 UTC, atinux approved these changes
👏

2017-09-18 06:52 UTC, merged