Relecture de `async-data.md`
vuejs-fr/nuxt pull request #13
Opened 2017-09-16 14:40 UTC by Haeresis

Signed-off-by: Bruno Lesieur <bruno.lesieur@gmail.com>

2017-09-17 13:36 UTC, rspt requested changes

2017-09-17 13:36 UTC, rspt commented on en/guide/async-data.md
> +1. Retourner une `Promise`. Nuxt.js attends que la promesse soit résolue avant de faire le rendu du composant.
"attend"

2017-09-17 13:36 UTC, rspt commented on en/guide/async-data.md
> +Vous pouvez utiliser l'objet du contexte injecté à la propriété `asyncData` afin d'accéder aux données des routes dynamiques. Par example, les données des routes dynamiques peuvent être accédées en u
"Par exemple"

2017-09-17 13:36 UTC, rspt commented on en/guide/async-data.md
> +Nuxt.js ajoute la méthode `error(params)` au `context`, vous pouvez l'appeler pour afficher la page d'erreur. `params.statusCode` sera également utilisée pour faire le rendu avec le code de status ap
"code de statut"

2017-09-17 13:36 UTC, rspt commented on en/guide/async-data.md
> +Pour personnaliser la page d'erreur, consultez la [partie mises en page de la section vues](/guide/views#mises-en-page).
"mise en page"

2017-09-17 13:36 UTC, rspt commented on en/guide/async-data.md
> +Pour personnaliser la page d'erreur, consultez la [partie mises en page de la section vues](/guide/views#mises-en-page).
Est-ce qu'on capitaliserait le mot "vues" étant donné qu'il s'agit du nom d'une section?

2017-09-17 13:37 UTC, rspt commented on en/guide/async-data.md
> +Pour personnaliser la page d'erreur, consultez la [partie mises en page de la section vues](/guide/views#mises-en-page).
Même question pour "Mises en page".

2017-09-17 17:07 UTC, atinux approved these changes
Top ! Je suis du meme avis que @rspt concernant les liens.

2017-09-18 07:13 UTC, Haeresis commented on en/guide/async-data.md
> +Pour personnaliser la page d'erreur, consultez la [partie mises en page de la section vues](/guide/views#mises-en-page).
C'est tout a fait possible oui. Pour le moment tous les liens déjà parcouru on été rédigé sans majuscule. Pour la consistence, je préfère revoir tous les liens précédents d'un coup.

Je vais jetter un œil rétroactivement si je peux faire ça dans cette PR vu que toutes les autres sont fusionnées.

2017-09-18 07:47 UTC, Haeresis commented
J'ai pris tes remarques en compte @rspt. Si c'est ok pour toi, je merge !

2017-09-18 10:28 UTC, rspt approved these changes

2017-09-18 10:29 UTC, rspt commented
> J'ai pris tes remarques en compte @rspt. Si c'est ok pour toi, je merge !

C'est tout bon pour moi @Haeresis 👏

2017-09-18 11:16 UTC, merged

2017-09-18 15:28 UTC, rspt commented on en/guide/routing.md
> +<p class="Alert Alert--info"><b>Attention :</b> les routes dynamiques sont ignorées par la commande `generate`, consultez la configuration de l'API pour La propriété `generate`](/api/configuration-ge
Même question également pour les noms de section que sur la PR #14 ?

2017-09-18 15:28 UTC, rspt commented on en/guide/routing.md
> +<p class="Alert Alert--info"><b>Attention :</b> les routes dynamiques sont ignorées par la commande `generate`, consultez la configuration de l'API pour La propriété `generate`](/api/configuration-ge
Est-ce qu'il ne manquerais pas un '['?

2017-09-18 15:29 UTC, rspt commented on en/guide/routing.md
> +<p class="Alert Alert--info"><b>Attention :</b> les routes dynamiques sont ignorées par la commande `generate`, consultez la configuration de l'API pour La propriété `generate`](/api/configuration-ge
Est-ce qu'il ne manquerais pas un '['?

2017-09-18 15:57 UTC, Haeresis commented on en/guide/routing.md
> +<p class="Alert Alert--info"><b>Attention :</b> les routes dynamiques sont ignorées par la commande `generate`, consultez la configuration de l'API pour La propriété `generate`](/api/configuration-ge
Cette fois c'est le bon nom de page :)

2017-09-18 15:58 UTC, Haeresis commented on en/guide/routing.md
> +<p class="Alert Alert--info"><b>Attention :</b> les routes dynamiques sont ignorées par la commande `generate`, consultez la configuration de l'API pour La propriété `generate`](/api/configuration-ge
Oui bien vu. Je commit ça : https://github.com/vuejs-fr/nuxt/commit/8768bc4c00d06fef9223d62df427cbcc0f360abd

2017-09-18 16:31 UTC, rspt commented on en/guide/routing.md
> +<p class="Alert Alert--info"><b>Attention :</b> les routes dynamiques sont ignorées par la commande `generate`, consultez la configuration de l'API pour La propriété `generate`](/api/configuration-ge
👏