Relecture de `assets.md`
vuejs-fr/nuxt pull request #14
Opened 2017-09-18 13:38 UTC by Haeresis

Go les assets

2017-09-18 13:51 UTC, atinux approved these changes

2017-09-18 14:06 UTC, rspt requested changes

2017-09-18 14:06 UTC, rspt commented on en/guide/assets.md
> +Par défaut, [vue-loader](http://vue-loader.vuejs.org/en/) traite automatiquement vos fichiers de style et vos templates à l'aide de `css-loader` et du compilateur de template de Vue. Dans ce processu
"vos fichiers de styles"

2017-09-18 14:06 UTC, rspt commented on en/guide/assets.md
> +- url-loader vous permet d'insérer de façon conditionnelle un fichier en tant qu'URL encodé en base 64 si sa taille est inférieure à un seuil donné. Cela peut réduire un certain nombre de demandes HT
"URL encodée"

2017-09-18 14:06 UTC, rspt commented on en/guide/assets.md
> +- url-loader vous permet d'insérer de façon conditionnelle un fichier en tant qu'URL encodé en base 64 si sa taille est inférieure à un seuil donné. Cela peut réduire un certain nombre de demandes HT
J'accorderais "taille" et "supérieur" -> "Si la taille du fichier est supérieure"

2017-09-18 14:06 UTC, rspt commented on en/guide/assets.md
> +Si vous désirez modifier ou désactiver ces loaders, consultez la documentation sur [La propriété `extend`](/api/configuration-build#extend).
"[la propriété `extend`]"

2017-09-18 14:06 UTC, rspt commented on en/guide/assets.md
> +À partir de votre code vous pouvez ensuite référencer ces fichiers avec de URL commencant par `/` :
"de URL"?

2017-09-18 14:50 UTC, Haeresis commented on en/guide/assets.md
> +- url-loader vous permet d'insérer de façon conditionnelle un fichier en tant qu'URL encodé en base 64 si sa taille est inférieure à un seuil donné. Cela peut réduire un certain nombre de demandes HT
Dans tout les projets Vue nous utilisons la voie masculine pour un URL à savoir, un Uniform Resource Locator, c.-à-d. un localisateur uniforme de ressource.

URL est invariable en français aussi URLs n'est pas valide. Par contre une URL n'est pas faux du tout car le genre est « hésitant ». C'est juste qu'on prend le parti masculin, je pense continuer ainsi pour Nuxt.
— https://fr.wiktionary.org/wiki/URL

Idem nous utilisons le terme la SEO pour la Search Engine Optimization soit l'optimisation pour moteur de recherche.

2017-09-18 14:50 UTC, Haeresis commented on en/guide/assets.md
> +- url-loader vous permet d'insérer de façon conditionnelle un fichier en tant qu'URL encodé en base 64 si sa taille est inférieure à un seuil donné. Cela peut réduire un certain nombre de demandes HT
Et oui à l'orale je dis une URL et une Game Cube. Je fais des efforts tout de même pour rectifier ça :D

2017-09-18 14:50 UTC, Haeresis commented on en/guide/assets.md
> +Si vous désirez modifier ou désactiver ces loaders, consultez la documentation sur [La propriété `extend`](/api/configuration-build#extend).
J'utilise la norme que nous avons établie ce matin même. La page aura pour titre « La propriété `extend` » donc majuscule. (Tu te souviens Mises en page et Vue) ;)

2017-09-18 15:16 UTC, rspt commented on en/guide/assets.md
> +- url-loader vous permet d'insérer de façon conditionnelle un fichier en tant qu'URL encodé en base 64 si sa taille est inférieure à un seuil donné. Cela peut réduire un certain nombre de demandes HT
Je t'avoue que j'utilise également le féminin pour URL (et pour Game Cube ^^).

Utilisons URL au masculin alors (et je me ferais au terme féminin SEO)

2017-09-18 15:17 UTC, rspt commented on en/guide/assets.md
> +Si vous désirez modifier ou désactiver ces loaders, consultez la documentation sur [La propriété `extend`](/api/configuration-build#extend).
Oui, et j'ai été voir la section qui s'appelle uniquement `extend` non? ^^

2017-09-18 15:23 UTC, rspt commented on en/guide/assets.md
> +Si vous désirez modifier ou désactiver ces loaders, consultez la documentation sur [La propriété `extend`](/api/configuration-build#extend).
Est-ce qu'on utiliserait pas plutôt "[la propriété `extend` de la page Propriété]" dans ce cas?

2017-09-18 15:26 UTC, Haeresis commented on en/guide/assets.md
> +Si vous désirez modifier ou désactiver ces loaders, consultez la documentation sur [La propriété `extend`](/api/configuration-build#extend).
Autant pour moi

2017-09-18 15:30 UTC, Haeresis commented on en/guide/assets.md
> +- url-loader vous permet d'insérer de façon conditionnelle un fichier en tant qu'URL encodé en base 64 si sa taille est inférieure à un seuil donné. Cela peut réduire un certain nombre de demandes HT
D'après un sondage Twitter seulement 20% des sondé disent la SEO. Moi ce qui m'a étonné c'est que quand même 20% disait la SEO XD

2017-09-18 15:31 UTC, rspt commented on en/guide/assets.md
> +- url-loader vous permet d'insérer de façon conditionnelle un fichier en tant qu'URL encodé en base 64 si sa taille est inférieure à un seuil donné. Cela peut réduire un certain nombre de demandes HT
> D'après un sondage Twitter seulement 20% des sondé disent la SEO. Moi ce qui m'a étonné c'est que quand même 20% disait la SEO XD

Ahahahah exact. Bon du coup celui-ci c'est ok!

2017-09-18 15:41 UTC, Haeresis commented
Merci pour ta revue et ton œil vif @rspt ! C'est tout bon normalement.

2017-09-18 15:45 UTC, rspt approved these changes

2017-09-19 06:29 UTC, forresst requested changes
2 petites remarques

2017-09-19 06:29 UTC, forresst commented on en/guide/assets.md
> +Puisque que les fichiers `.png` ne sont pas des fichiers JavaScript, Nuxt.js configure webpack afin d'utiliser [file-loader](https://github.com/webpack/file-loader) et [url-loader](https://github.com
Nuxt.js configure webpack ~~afin d'~~ **pour** utiliser [file-loader](https://github.com/webpack/file-loader) et [url-loader](https://github.com/webpack/url-loader) afin de ~~pouvoir~~ s'en charger **à votre place**.
> cela permet d'éviter la répétition de "afin"

2017-09-19 06:29 UTC, forresst commented on en/guide/assets.md
> +Lors du lancement de notre application avec `nuxt`, notre modèle dans `pages/index.vue` :
modèle => template
> je laisserai "template" puisque c'est la balise dans le fichier .vue

2017-09-20 07:01 UTC, Haeresis commented on en/guide/assets.md
> +Lors du lancement de notre application avec `nuxt`, notre modèle dans `pages/index.vue` :
Tout à fait !

2017-09-20 07:02 UTC, Haeresis commented
Merce @forresst ! Bon pour merge ?

2017-09-20 09:52 UTC, forresst approved these changes

2017-09-20 10:58 UTC, forresst commented
C'est bon pour moi 👏

2017-09-20 11:01 UTC, merged