Traduction de `modules.md`
vuejs-fr/nuxt pull request #21
Opened 2017-09-30 10:39 UTC by Haeresis

Je commence cette traduction. Je laisse cette PR pour recueiller vos avis à l'avance si vous le souhaitez !

2017-09-30 12:26 UTC, Haeresis commented
Je corrige les fautes d'ortho que j'arrive a trouver et je passe ça en relecture !

2017-09-30 12:45 UTC, Haeresis commented
Voilà c'est prêt ! Pas d'inquiétude pour le nombre de ligne qui diffère, j'ai déjà PR l'original avec les changements clean qui vont bien ! https://github.com/nuxt/docs/pull/267

2017-09-30 14:13 UTC, rspt requested changes

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +C'est pourquoi Nuxt introduit un système modulaire d'ordre supérieur pour facilement étendre ses fonctionnalités de base. Les modules sont en fait des **fonctions** qui sont appelées de manière séque
"chacun d'entre eux soit chargé"

Accord avec chacun qui est invariable

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +- Vous êtes un développeur flaimard et vous n'aimez pas vous encombrer avec des détails comme le paramétrage de chaque nouvelle bibliothèque ou intégration (quelqu'un l'aura surement déjà fait pour v
"flémard"

J'éviterais flémard/paresseux. Pour moi dans ce contexte c'est plutôt être un développeur futé ;)

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +- Vous êtes fatigué de l'utilisation des API bas niveau et de leur changement continue et vous souhaiter **simplement des choses fonctionnelles**.
"changement continu"

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +Comme précédemment mentionné, les modules sont juste de simples fonctions. Ils peuvent être packagés en tant que modules npm ou directement inclus dans le code source du projet.
"Comme précédemment mentionnés,"

Accord avec "modules"

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +Vous pouvez accéder directement aux options de Nuxt en utilisant cette référence. C'est la configuration `nuxt.config.js` avec ses options par défaut assignées qui peut être utilisées en tant qu'opti
"qui peuvent être"

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +<p class="Alert Alert--orange">Faites attention avec `async` et `await`, ils sont supportés uniquement depuis Node.js 7.2+. Donc si vous êtes un développeur de modules, n'oubliez pas d'avertir vos ut
"version antérieure"

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +Parfois il est plus simple d'utiliser des options de hauts niveaux lors de l'abonnement de modules à `nuxt.config.js`. Donc nous pouvons combiner les options de sources multiples.
"haut niveau"

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +Il est courant que les modules fournissent un ou plusieurs plugins quand ils sont ajoutés. Par exemple le module [bootstrap-vue](https://bootstrap-vue.js.org) nécessite d'être enregistrer lui-même da
"d'être enregistré"

2017-09-30 14:13 UTC, rspt commented on en/guide/modules.md
> +      // Personnalisation des loaders existant
"Personnalisation des loaders existants"

2017-09-30 15:07 UTC, MachinisteWeb reviewed
Merci @rspt ! C'est dans la boîte. Juste une proposition de « occupé » à la place de « flémard »

2017-09-30 15:07 UTC, Haeresis commented on en/guide/modules.md
> +- Vous êtes un développeur flaimard et vous n'aimez pas vous encombrer avec des détails comme le paramétrage de chaque nouvelle bibliothèque ou intégration (quelqu'un l'aura surement déjà fait pour v
Mais un bon développeur est un développeur flémard !

Le terme est probablement péjoratif. Mais je suis pas sur non plus que se soit futé qui conviennent ici. Je vais opter pour « occupé »

2017-10-01 08:04 UTC, rspt commented on en/guide/modules.md
> +- Vous êtes un développeur flaimard et vous n'aimez pas vous encombrer avec des détails comme le paramétrage de chaque nouvelle bibliothèque ou intégration (quelqu'un l'aura surement déjà fait pour v
> Mais un bon développeur est un développeur flémar

Ahahah oui je plussoie ^^

> Le terme est probablement péjoratif. Mais je suis pas sur non plus que se soit futé qui conviennent ici. Je vais opter pour « occupé »

Parfait!

2017-10-01 08:04 UTC, rspt approved these changes

2017-10-02 07:34 UTC, Haeresis commented
Top @rspt ! @Kocal ou @forresst ? Une seconde relecture ?

2017-10-02 11:11 UTC, forresst requested changes
Quelques erreurs et remarques

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +Pendant votre phase d'amélioration du passage du développement à la production avec Nuxt, vous allez découvrir que les fonctionnalités offertes par celui-ci ne sont pas complètes. Faire la configurat
Tout en développant une application de qualité du niveau de la production en utilisant Nuxt, ...
> la traduction actuelle me paraît incorrecte

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +      // Nuxt va remplacer `options.ua` par `123` quand il va copier le plugin au projet.
va remplacer => remplacera
va copier => copiera

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +    // Ajouter Font Awesome
Ajouter => Ajoute

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +        // La source peut être mise en tampon aussi
La source peut être **aussi** mise en tampon ~~aussi~~

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +    // Ceci va être appelé quand tous les modules auront fini d'être chargés
va être => sera

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +  // Ajouter un point d'ancrage au module
Ajouter => Ajoute

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +  // Ajouter un point d'ancrage au moteur de rendu
Ajouter => Ajoute

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +    // Ceci va être appelé quand le moteur de rendu aura été créé
va être => sera

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +  // Ajouter un point d'ancrage au build
Ajouter => Ajoute

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +    // Ceci va être appelé une fois le build fait
va être => sera

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +        // Ceci va être lancé juste avant que le compilateur de webpack démarre
va être => sera

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +  // Ajouter un point d'ancrage à la génération
Ajouter => Ajoute

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +    // Ceci va être appelé quand la génération de Nuxt va commencer
va être => sera

2017-10-02 11:11 UTC, forresst commented on en/guide/modules.md
> +<p class="Alert">Il y a encore bien de points d'ancrage et de possibilités pour les modules. Consultez les [mécanismes de Nuxt](/api/internals) pour en apprendre plus à propos de l'API interne de Nux
Il y a encore bien de points d'ancrage => Il existe beaucoup d'autres points d'ancrage

2017-10-02 11:54 UTC, Haeresis commented on en/guide/modules.md
> +Pendant votre phase d'amélioration du passage du développement à la production avec Nuxt, vous allez découvrir que les fonctionnalités offertes par celui-ci ne sont pas complètes. Faire la configurat
Oui. J'ai bloqué sur cette traduction. Je trouve ta proposition étrange aussi cependant :)

Que penses-tu tout simplement de « Pendant la phase d'amélioration de votre application pour la production » ?

Parceque ce dont il est question ici, c'est exactement ça : tout ce que vous aller améliorer dans votre application pour qu'elle soit optimisée pour la production et facile à mettre en production. Et il s'avère que dans cette quête, on va utiliser plus que ce que fournit Nuxt de base.

2017-10-02 11:54 UTC, Haeresis commented on en/guide/modules.md
> +    // Ajouter Font Awesome
Je vais mettre « Ajout de ». Ce qui me gène avec « ajoute » c'est que c'est typiquement la description de ce que fait une méthode. Hors là c'est pas vraiment le cas, c'est surtout l'utilisateur qui fait l'action en augmentant le nombre d'élément dans l'option `css`.

2017-10-02 12:30 UTC, forresst commented on en/guide/modules.md
> +Pendant votre phase d'amélioration du passage du développement à la production avec Nuxt, vous allez découvrir que les fonctionnalités offertes par celui-ci ne sont pas complètes. Faire la configurat
Pendant la phase d'amélioration de votre application pour la production 
> 👍

2017-10-02 12:34 UTC, forresst requested changes
Des oublis (désolé)

2017-10-02 12:34 UTC, forresst commented on en/guide/modules.md
> +    // Ceci va être appelé quand la génération de Nuxt va commencer
Ceci va être appelé quand la génération de Nuxt va commencer => Ceci sera appelé quand la génération de Nuxt commencera

2017-10-02 12:34 UTC, forresst commented on en/guide/modules.md
> +    // Ceci va être appelé une fois le build fait
Ceci va être appelé une fois le build fait => Ceci sera appelé une fois le build fait

2017-10-02 12:34 UTC, forresst commented on en/guide/modules.md
> +    // Ceci va être appelé quand le moteur de rendu aura été créé
Ceci va être appelé quand le moteur de rendu aura été créé => Ceci sera appelé quand le moteur de rendu aura été créé

2017-10-02 12:34 UTC, forresst commented on en/guide/modules.md
> +    // Ceci va être appelé quand tous les modules auront fini d'être chargés
Ceci va être appelé quand tous les modules auront fini d'être chargés => Ceci sera appelé quand tous les modules auront fini d'être chargés

2017-10-02 14:01 UTC, Haeresis commented
Pas de soucis @forresst !

C'est dans la boîte !

2017-10-02 14:22 UTC, merged

2017-10-02 14:23 UTC, Haeresis commented
Le site fr part live ! Je voudrais passer cette dernière page. Si il y a encore des soucis, je les ajouterais manuellement dans la prochaine monté !