Traduction de `context.md`
vuejs-fr/nuxt pull request #25
Opened 2017-10-12 12:08 UTC by Haeresis

Nouveau fichier traduit. Merci infiniment à @rspt pour le travail déjà effectué es surtout à @forresst qui review toutes les PR et que je n'ai malheureusement pas pu mentionner sur la PR Nuxt. Mais pour me faire pardonner Vuejs-FR pointe sur notre liste de crédits où j'y mentionne également les reviewers ;)

2017-10-12 13:39 UTC, rspt requested changes

2017-10-12 13:39 UTC, rspt commented on en/api/context.md
> +| `isHMR`                | `Boolean`                                                                          | Client et serveur | Valeur booléenne vous permettant de savoir les méthodes et middlewa
Si middleware est masculin -> "appelés"

2017-10-12 13:39 UTC, rspt commented on en/api/context.md
> +| `req`                  | [`http.Request`](https://nodejs.org/api/http.html#http_class_http_incomingmessage) | Serveur           | Requête faites au serveur Node.js. Si Nuxt est utilisé en tant que
"Requête faite"

2017-10-12 13:39 UTC, rspt commented on en/api/context.md
> +| `res`                  | [`http.Response`](https://nodejs.org/api/http.html#http_class_http_serverresponse) | Serveur           | Réponse faites par le serveur Node.js. Si Nuxt est utilisé en tant
"Réponse faite"

2017-10-12 13:39 UTC, rspt commented on en/api/context.md
> +| `redirect`             | `Function`                                                                         | Client et serveur | Cette methode redirige l'utilisateur vers une autre route, un code
méthode

2017-10-12 13:39 UTC, rspt commented on en/api/context.md
> +| `error`                | `Function`                                                                         | Client et serveur | Cette methode montre la page d'erreur : `error(params)`. L'objet `p
méthode

2017-10-12 13:39 UTC, rspt commented on en/api/context.md
> +| `beforeNuxtRender(fn)` | `Function`                                                                         | Serveur           | Cette methode met à jour la variable `__NUXT__` rendue côté client,
méthode

2017-10-12 13:39 UTC, rspt commented on en/api/context.md
> +| `nuxtState`            | `Object`                                                                           | Client            | L'état de Nuxt, utile pour les plugins qui utilisent `beforeNuxtRen
connaitre

2017-10-12 14:29 UTC, Haeresis commented on en/api/context.md
> +| `isHMR`                | `Boolean`                                                                          | Client et serveur | Valeur booléenne vous permettant de savoir les méthodes et middlewa
Oui c'est un p'tit gars !

2017-10-12 14:32 UTC, Haeresis commented on en/api/context.md
> +| `nuxtState`            | `Object`                                                                           | Client            | L'état de Nuxt, utile pour les plugins qui utilisent `beforeNuxtRen
Arf, dur dur les vieilles habitudes pre 1990 :D

2017-10-12 14:47 UTC, forresst requested changes
Quelques remarques ...

2017-10-12 14:47 UTC, forresst commented on en/api/context.md
> +description: L'objet `context` fournit des objets et paramètres additionnels en provenance de Nuxt qui ne sont pas disponibles dans les composants Vue natifs. Le `context` est disponible dans des air
qui ne sont pas **traditionnellement* disponibles dans les composants Vue ~~natifs~~
> le mot "natifs" me gêne, j'ai l'impression qu'on parle uniquement des composants Vue fait par la team Vue.

2017-10-12 14:47 UTC, forresst commented on en/api/context.md
> +| `isDev`                | `Boolean`                                                                          | Client et serveur | Valeur booléenne vous permettant de savoir si vous êtes en mode dév
en mode développement, **ceci** peut-être utile
> j'ajouterais le mot "ceci"

2017-10-12 14:47 UTC, forresst commented on en/api/context.md
> +| `isHMR`                | `Boolean`                                                                          | Client et serveur | Valeur booléenne vous permettant de savoir les méthodes et middlewa
vous permettant de savoir **si** les méthodes et middlewares
> manque le mot "si"

2017-10-12 14:47 UTC, forresst commented on en/api/context.md
> +| `env`                  | `Object`                                                                           | Client et serveur | Environment variables set in `nuxt.config.js`, see [env api](/api/c
Variables d'environnement définies dans `nuxt.config.js`, consulter [env dans l'api](/api/configuration-env)
> un petit oubli de traduction

2017-10-12 14:47 UTC, forresst commented on en/api/context.md
> +| `error`                | `Function`                                                                         | Client et serveur | Cette méthode montre la page d'erreur : `error(params)`. L'objet `p
devrait avoir ~~la propriétés~~ **les champs** `statusCode` et `message`.
> ou "les propriétés"

2017-10-12 14:51 UTC, forresst commented
> surtout à @forresst qui review toutes les PR et que je n'ai malheureusement pas pu mentionner sur la PR
@Haeresis @rspt je préfére laisser les couronnes à ceux qui le méritent 🥇

2017-10-12 15:16 UTC, Haeresis commented on en/api/context.md
> +| `error`                | `Function`                                                                         | Client et serveur | Cette méthode montre la page d'erreur : `error(params)`. L'objet `p
les propriétés

2017-10-12 16:51 UTC, forresst approved these changes

2017-10-12 19:50 UTC, rspt approved these changes

2017-10-12 19:52 UTC, rspt commented
> @Haeresis @rspt je préfère laisser les couronnes à ceux qui le méritent 🥇

Surtout heureusement que vous êtes passé par là, je n'avais pas beaucoup de temps à y consacrer et ça m'a remotivé :)

2017-10-13 09:04 UTC, Atinux commented
Je n'ai pas trop de temps pour review ces PR, mais je vous fait entierement confiance @rspt @forresst @Haeresis, merci encore pour votre aide precieuse a la communaute francophone :)

PS: J'ai pas d'accent sur le clavier avec lequel j'ecris...

2017-10-13 09:23 UTC, Haeresis commented
> PS: J'ai pas d'accent sur le clavier avec lequel j'ecris...

🤣

2017-10-13 09:23 UTC, merged