Pages API part
vuejs-fr/nuxt pull request #26
Opened 2017-10-13 14:14 UTC by Haeresis

C'est au tour de la partie « Pages » des API

2017-10-13 15:02 UTC, rspt requested changes

2017-10-13 15:02 UTC, rspt commented on en/api/index.md
> +<div class="Alert Alert--orange">Vous **n**'avez **PAS** accès à l'instance du composant via `this` au sein de `asyncData` parce que la fonciton est appelée **avant d'initialiser** le composant.</div
"fonction"

2017-10-13 15:02 UTC, rspt commented on en/api/pages-head.md
> +<p class="Alert">Afin d'éviter les doublons quand vous utilisez un composant enfant, utilisez un identifiant unique à l'aide de la clef `hid`. En savoir [plus à ce propos](https://github.com/declande
"clé" (graphie rectifiée)

2017-10-13 15:02 UTC, rspt commented on en/api/pages-layout.md
> +> Chaque fichier (premier niveau) dans le répertoire `layouts` créera une mise en page personnalisé accessible avec la propriété `layout` dans le composant de page.
"personnalisée"

2017-10-13 15:02 UTC, rspt commented on en/api/pages-layout.md
> +Dans cet exemple, Nuxt.js incluera le fichier `layouts/blog.vue` comme mise en page pour ce composant de page.
"inclura"

2017-10-13 15:02 UTC, rspt commented on en/api/pages-middleware.md
> +Pour en savoir plus sur les middleware, voir le [guide middleware](/guide/routing#middleware).
Je mettrais "middlewares"

2017-10-13 15:02 UTC, rspt commented on en/api/pages-transition.md
> +Pour définir une transition personalisée pour une route spécifique, ajouter la propriété `transition` au composant de page.
"personnalisée"

2017-10-13 15:02 UTC, rspt commented on en/api/pages-transition.md
> +| `duration`         | `Integer` | aucune     | La dunée (en millisecondes) appliqué a une transition, voir la [documentation Vue.js](https://fr.vuejs.org/v2/guide/transitions.html#Durees-de-transiti
"La durée (en millisecondes) appliquée"

2017-10-13 15:02 UTC, rspt commented on en/api/pages-validate.md
> +Vous pouvez également utiliser des données de votre [store](/guide/vuex-store) pour la validation comme par exemple remplie par l'action [`nuxtServerInit`](/guide/vuex-store#the-nuxtserverinit-action
Tournure de phrase bizarre. De plus, "comme par exemple" est un pléonasme :)

2017-10-13 16:09 UTC, Haeresis commented
Merci @rspt ! C'est dans la boîte !

2017-10-13 17:21 UTC, rspt approved these changes

2017-10-14 06:10 UTC, forresst requested changes
Quelques erreurs et remarques

2017-10-14 06:10 UTC, forresst commented on en/api/index.md
> +<div class="Alert Alert--orange">Vous **n**'avez **PAS** accès à l'instance du composant via `this` au sein de `asyncData` parce que la fonction est appelée **avant d'initialiser** le composant.</div
Vous **n**'avez **PAS** => Vous **N**'avez **PAS**
> Le N en majuscule

2017-10-14 06:10 UTC, forresst commented on en/api/pages-fetch.md
> +Vous pouvez également utiliser `async` / `await` pour rendre votre code plus propre:
plus propre : 
> il manque un espace entre "propre" et ":"

2017-10-14 06:10 UTC, forresst commented on en/api/pages-head.md
> +description: Nuxt.js utilise vue-meta pour mettre à jours les entêtes et les attributs HTML de votre application.
mettre à jour
> il faut enlever le "s" à "jours"

2017-10-14 06:10 UTC, forresst commented on en/api/pages-head.md
> +> Nuxt.js utilise [vue-meta](https://github.com/declandewet/vue-meta) pour mettre à jours les entêtes et les attributs HTML de votre application.
mettre à jour
> il faut enlever le "s" à "jours"

2017-10-14 06:10 UTC, forresst commented on en/api/pages-layout.md
> +- **Type :** `String` ou `Function` (défaut : `'default'`)
(défaut : `'default'`) => (par défaut : `'default'`)
> je rajouterais "par"

2017-10-14 06:10 UTC, forresst commented on en/api/pages-scrolltotop.md
> +description: La propriété `scrollToTop` vous permet d'indiquer à Nuxt.js de défiler la page tout en avant de faire le rendu.
de défiler la page tout en avant de faire le rendu. => de **faire** défiler la page tout en **haut** avant de faire le rendu.

2017-10-14 06:10 UTC, forresst commented on en/api/pages-scrolltotop.md
> +> La propriété `scrollToTop` vous permet d'indiquer à Nuxt.js de défiler la page tout en avant de faire le rendu.
de défiler la page tout en avant de faire le rendu. => de **faire** défiler la page tout en **haut** avant de faire le rendu.

2017-10-14 06:10 UTC, forresst commented on en/api/pages-scrolltotop.md
> +Si vous désirez écraser le comportonent par défaut au défilement, regardez l'[option `scrollBehavior`](/api/configuration-router#scrollBehavior).
comportonent => comportement

par défaut ~~au~~ **du** défilement

2017-10-14 06:10 UTC, forresst commented on en/api/pages-transition.md
> +Pour définir une transition personnalisée pour une route spécifique, ajouter la propriété `transition` au composant de page.
ajouter => ajoutez

2017-10-14 06:10 UTC, forresst commented on en/api/pages-transition.md
> +Si la propriété `transition` est défini en tant que chaine de caractère, il sera utilisé comme `transition.name`.
défini => définie
> c'est la propriété qui est définie

Il sera utilisé => elle sera utilisée
> on parle de la propriété ?

2017-10-14 06:10 UTC, forresst commented on en/api/pages-transition.md
> +| `css`              | `Boolean` | `true`     | Défini s'il faut utiliser les transitions de classes CSS. Par défaut à `true`. Si mis à `false`, ne déclenchera que les points d'ancrage JavaScript abo
à `false`, **cela** ne déclenchera
> je rajouterais "cela"

2017-10-14 06:10 UTC, forresst commented on en/api/pages-validate.md
> +Vous pouvez vérifier aussi vérifier des données de votre [store](/guide/vuex-store) (remplies au préalable avec l'action [`nuxtServerInit`](/guide/vuex-store#the-nuxtserverinit-action)) :
Vous pouvez ~~vérifier~~ aussi vérifier ~~des~~ **les** données ~~de~~ **dans** votre
> Vous pouvez aussi vérifier les données dans votre

2017-10-14 07:29 UTC, Haeresis commented
Merci beaucoup @forresst pour ton œil de Lynx (ou peux importe ton navigateur) !

2017-10-14 08:42 UTC, forresst approved these changes

2017-10-14 09:53 UTC, merged

2017-10-15 19:29 UTC, forresst commented
Je sais pas comment ça se fait, mais la page asyncData n'est pas traduite (https://fr.nuxtjs.org/api/)

2017-10-16 07:38 UTC, Haeresis commented
Je m'occupe de tout ça dans la matinée