Pages api
vuejs-fr/nuxt pull request #27
Opened 2017-10-16 16:01 UTC by Haeresis

2017-10-16 16:19 UTC, rspt requested changes

2017-10-16 16:19 UTC, rspt commented on en/api/components-nuxt-link.md
> +Actuellement, `<nuxt-link>` est identique à [`<router-link>`](https://router.vuejs.org/fr/api/router-link.html). Nous vous recommendons d'apprendre à l'utiliser avec la [documentation de Vue Router](
recommandons

2017-10-16 17:01 UTC, Haeresis commented
Merci @rspt

2017-10-16 21:06 UTC, rspt approved these changes

2017-10-17 05:20 UTC, forresst approved these changes
C'est tout bon pour moi

2017-10-17 08:51 UTC, Haeresis commented
Merci @forresst !

2017-10-17 08:52 UTC, merged