Traduction de `api/nuxt-*`
vuejs-fr/nuxt pull request #28
Opened 2017-10-24 14:37 UTC by Haeresis

4 nouveaux fichiers à revoir :)

2017-10-24 14:53 UTC, rspt requested changes

2017-10-24 14:53 UTC, rspt commented on en/api/nuxt-render-and-get-window.md
> +<p class="Alert Alert--info">Cette méthode est faites pour les [tests](guide/development-tools#tests-de-bout-en-bout).</p>
"est faite"

2017-10-24 14:53 UTC, rspt commented on en/api/nuxt-render-route.md
> +Cette méthode devrait être utilisé en particulier pour les [tests](guide/development-tools#tests-de-bout-en-bout) aussi bien que [`nuxt.renderAndGetWindow`](/api/nuxt-render-and-get-window).
"être utilisée"

2017-10-24 14:53 UTC, rspt commented on en/api/nuxt-render-route.md
> +  // `html` sera toujour une chaine de caractères
"sera toujours"

2017-10-24 14:53 UTC, rspt commented on en/api/nuxt-render.md
> +// Nous instantion Nuxt.js avec les options
"Nous instancions" non?

2017-10-24 14:53 UTC, rspt commented on en/api/nuxt-render.md
> +<p class="Alert">Il est recommandé d'appeler `nuxt.render` à la fin de votre middlewares ainsi il ferra le rendu de votre application web et n'appelera pas `next()`.</p>
"il fera le rendu de votre application web et n'appellera"

2017-10-24 18:44 UTC, rspt approved these changes

2017-10-26 07:41 UTC, merged

2017-10-31 07:20 UTC, forresst reviewed
Désolé, pas dispo la semaine dernière, mais j'ai vu quelques erreurs

2017-10-31 07:20 UTC, forresst commented on en/api/nuxt-render-and-get-window.md
> +description: Obtient la `window` à une URL donnée d'une application Nuxt.js.
Obtient la `window` ~~à~~ **depuis** une URL donnée d'une application Nuxt.js.

2017-10-31 07:20 UTC, forresst commented on en/api/nuxt-render-and-get-window.md
> +> Obtient la `window` à une URL donnée d'une application Nuxt.js.
Obtient la `window` ~~à~~ **depuis** une URL donnée d'une application Nuxt.js.

2017-10-31 07:20 UTC, forresst commented on en/api/nuxt-render-route.md
> +  // { statusCode: 500, message: 'Mon message d'erreur' }
{ statusCode: 500, message: 'Mon message d'erreur' } => { statusCode: 500, message: 'Mon message d erreur' }
> Bien que ce soit un commentaire, j’enlèverai l'apostrophe entre le "d" et "erreur", je sais je suis tatillons quelquefois :smile: (sinon il y a une erreur de syntaxe javascript)

2017-10-31 07:20 UTC, forresst commented on en/api/nuxt-render.md
> +<p class="Alert">Il est recommandé d'appeler `nuxt.render` à la fin de votre middlewares ainsi il fera le rendu de votre application web et n'appellera pas `next()`.</p>
à la fin de votre middlewares => à la fin de vos middlewares