Traduction de `configuration-build.md`
vuejs-fr/nuxt pull request #31
Opened 2017-11-20 10:39 UTC by Haeresis

Début de la dernière étape, la configuration Nuxt.

2017-11-20 18:30 UTC, rspt requested changes

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +- Par défault : `true` en développement et `false` en production.
"Par défaut"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +- Par défault :
"Par défaut"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +2. un object avec les propriétés suivantes (toutes booléenes): `dev`, `isClient`, `isServer`.
"un objet"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +2. un object avec les propriétés suivantes (toutes booléenes): `dev`, `isClient`, `isServer`.
"booléennes" non?

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +Utiliser `extract-text-webpack-plugin` pour extraire le CSS du fragment principale dans un fichier CSS séparé (injection automatique avec template), permet au fichier d'être mis en cache de manière i
"fragment principal"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +Utiliser `extract-text-webpack-plugin` pour extraire le CSS du fragment principale dans un fichier CSS séparé (injection automatique avec template), permet au fichier d'être mis en cache de manière i
"beaucoup de fichiers"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +Utiliser `extract-text-webpack-plugin` pour extraire le CSS du fragment principale dans un fichier CSS séparé (injection automatique avec template), permet au fichier d'être mis en cache de manière i
"vont rester"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +  **Note :** alors que l'usage par défaut est OK et assez flexible pour des cas d'utilisations normaux, l'utilisation recommandée par [`vue-loader`](https://vue-loader.vuejs.org/en/options.html#postc
"est d'utiliser"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +Cette option est automatiquement créer en se basant sur la valeur de  `mode` si elle n'est pas fournie.
"créée"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +> Nuxt.js vous permet de fournir vos propres templates qui seront rendu en ce basant sur la configuration de Nuxt. Cette fonctionnalité est particulièrement utile quand utilisé avec [modules](/guide/
"seront rendus"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +> Nuxt.js vous permet de fournir vos propres templates qui seront rendu en ce basant sur la configuration de Nuxt. Cette fonctionnalité est particulièrement utile quand utilisé avec [modules](/guide/
"en se basant"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +> Nuxt.js vous permet de fournir vos propres templates qui seront rendu en ce basant sur la configuration de Nuxt. Cette fonctionnalité est particulièrement utile quand utilisé avec [modules](/guide/
"quand utilisée"

2017-11-20 18:30 UTC, rspt commented on en/api/configuration-build.md
> +Les templates sont rendu en utilisant [`lodash.template`](https://lodash.com/docs/#template). Vous pouvez en apprendre plus à propos de leur utilisation [ici](https://github.com/learn-co-students/jav
"sont rendus"

2017-11-21 14:03 UTC, rspt commented on en/api/configuration-build.md
> +2. un object avec les propriétés suivantes (toutes booléenes): `dev`, `isClient`, `isServer`.
@Haeresis t'as oublié le "un objet", dans le point 2

2017-11-21 14:04 UTC, Haeresis commented on en/api/configuration-build.md
> +2. un object avec les propriétés suivantes (toutes booléenes): `dev`, `isClient`, `isServer`.
Ah, j'avais pas compris, j'avais changé la première ligne.

2017-11-21 16:43 UTC, rspt approved these changes

2017-12-08 13:40 UTC, merged