Mise à jour de `routing.md`
vuejs-fr/nuxt pull request #34
Opened 2018-02-02 14:53 UTC by Haeresis

Hi tout le monde ! Besoin de quelques relectures sur cette PR !

2018-02-02 18:06 UTC, rspt requested changes

2018-02-02 18:06 UTC, rspt commented on en/guide/routing.md
> +Vous pouvez activer l'alternative pour application monopage pour les routes dynamiques aussi. Nuxt.js va générer un fichier supplémentaire identique à `index.html` qui pourra être utilisé en `mode: '
- "La plupart"

2018-02-05 15:17 UTC, Haeresis commented
Merci @rspt !

2018-02-05 15:39 UTC, rspt approved these changes

2018-02-05 16:08 UTC, forresst approved these changes

2018-02-06 10:09 UTC, merged