Traduction decomponents-no-ssr.m
vuejs-fr/nuxt pull request #35
Opened 2018-02-02 15:03 UTC by Haeresis

Re bonjour à tous, besoin de quelques relecture sur ce fichier !

2018-02-02 18:07 UTC, rspt requested changes

2018-02-02 18:07 UTC, rspt commented on en/api/components-no-ssr.md
> +title: "API: le componsant <no-ssr>"
"composant"

2018-02-05 15:24 UTC, Haeresis commented
Merci @rspt

2018-02-05 15:39 UTC, rspt approved these changes

2018-02-05 16:10 UTC, forresst approved these changes

2018-02-06 10:09 UTC, merged