Traduction de `configuration-css.md`
vuejs-fr/nuxt pull request #36
Opened 2018-02-02 15:27 UTC by Haeresis

Bonjour tlm, besoin de quelques relectures !

2018-02-02 18:08 UTC, rspt requested changes

2018-02-02 18:08 UTC, rspt commented on en/api/configuration-css.md
> +> Nuxt.js vous permet de définir le fichier, la bibliothèque ou le module CSS que vous souhaiter définir globalement (inclue sur toutes les pages).
"vous souhaitez"

2018-02-02 18:08 UTC, rspt commented on en/api/configuration-css.md
> +Dans le cas où vous souhaiteriez utiliser ```sass```, assurez-vous d'avoir installer les packages ```node-sass``` et ```sass-loader```. Si non, utilisez cette commande :
"installé"

2018-02-05 15:36 UTC, Haeresis commented
Merci @rspt !

2018-02-05 15:41 UTC, rspt approved these changes

2018-02-05 16:10 UTC, forresst approved these changes

2018-02-06 10:09 UTC, merged