Relecture de index.md
vuejs-fr/nuxt pull request #4
Opened 2017-09-14 11:27 UTC by Haeresis

On entamme la relecture

2017-09-15 12:17 UTC, rspt requested changes
Quelques corrections orthographiques :)

Merci pour le travail!

2017-09-15 12:17 UTC, rspt commented on en/guide/index.md
> +> Le 25 octobre 2016, l'équipe derrière [zeit.co](https://zeit.co/), annonçait [Next.js](https://zeit.co/blog/next), un framework pour les applications React rendues côté serveur. Quelques heures apr
J'ajouterais un "e" à évident.

2017-09-15 12:17 UTC, rspt commented on en/guide/index.md
> +- Pré-processeur : Sass, Less, Stylus, etc.
Préprocesseur

2017-09-15 12:17 UTC, rspt commented on en/guide/index.md
> +- En-tête HTTP/2 PUSH
Tout dépend de si on utilise la graphie rectifiée ou non. Si oui -> Entête

2017-09-15 12:17 UTC, rspt commented on en/guide/index.md
> +Si vous avez déjà un serveur, vous pouvez greffer Nuxt.js en l'utilisant comme middleware. Il n'y a aucune restrictions quand vous utilisez Nuxt.js pour développer votre application web universelle.
"restriction" sans "s"

2017-09-15 12:17 UTC, rspt commented on en/guide/index.md
> +Lors de la création de votre application, il générera le code HTML de chacune de vos routes pour le stocker dans un fichier.
De nouveau une question de graphie rectifiée ou non ^^. Si oui -> "génèrera"

2017-09-15 12:22 UTC, Haeresis commented on en/guide/index.md
> +Lors de la création de votre application, il générera le code HTML de chacune de vos routes pour le stocker dans un fichier.
Je préfère l'écriture d'après 1990 comme pour « évènement ». Merci !

2017-09-15 12:23 UTC, Haeresis commented
Merci pour tes retours @rspt ! C'est dans la boite.

2017-09-15 14:15 UTC, Kocal commented on en/guide/index.md
> +Son champ principal est de **faire le rendu d'interface utilisateur (« UI »)** en faisant abstraction de la distribution au client et au serveur.
> Son but principal

2017-09-15 14:26 UTC, Haeresis commented
J'avais aussi trouvé champ étrange tout en bloquant sur un bon terme équivalent. Merci @Kocal !

2017-09-16 05:47 UTC, forresst requested changes
Quelques remarques et erreurs, mais rien de bien méchant

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Notre but est de créer un framework suffisamment flexible afin que vous puissiez l'utiliser comme base dans un projet principal ou en tant que supplément pour votre projet actuel basé sur Node.js.
comme **une** base dans un projet
> j'ajouterai "une"

en ~~tant que supplément~~ **complément** pour votre projet actuel

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Nous croyons que cette option pourrait être la prochaine étape importante dans le développement d'applications web avec microservices.
avec **des** microservices
> manque "des"

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +En tant que framework, Nuxt.js est doté de nombreuses fonctionnalités pour vous aider dans votre développement entre côté client et serveur telles que les données asynchrones, les *middlewares*, les
dans votre développement entre ~~côté~~ **le** client et **le** serveur

telles que => tels que
> j'ai un doute entre le masculin et le féminin, je suis d'accord qu'on parle des fonctionnalités qui est féminin (donc ce serait logique de mettre "telles"), mais on énumère une liste de fonctionnalités (données, middlewares, layouts) qui sont aux masculin et féminin. Je ne sais pas qu'elle est la bonne règle ?!?

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Un total de seulement **57ko min+gzip** (53ko avec Vuex).
Pour l'unité kb n'est pas équivalente à ko: 
1 kilobit = 1 000 bits = 125 octets 

Je pense qu'il faut laisser kb

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +- [Vue Router](https://github.com/vuejs/vue-router)
Y'a t-il une raison d'enlever le "-" à Vue-Router et Vue-Meta, cela ne correspond pas à la version anglaise ?

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Sous le capot, nous utilisons [webpack](https://github.com/webpack/webpack) avec [vue-loader](https://github.com/vuejs/vue-loader) et [babel-loader](https://github.com/babel/babel-loader) pour empaqu
Webpack
> Webpack avec un W majuscule

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +- Utilisation des fichiers Vue (`*.vue*`)
Écriture des fichiers Vue
> Écriture me semble plus approprier pour traduire "Write"

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +En utilisant la commande `nuxt`, Nuxt va démarrer un serveur de développement avec rechargement à chaud et [Vue Server Renderer](https://ssr.vuejs.org/fr/) configurés afin de servir automatiquement l
Nuxt ~~va démarrer~~ **démarrera** un serveur de développement avec rechargement à chaud et [Vue Server Renderer](https://ssr.vuejs.org/fr/) ~~configurés~~ **sera configuré** ~~afin de servir~~ **pour faire** automatiquement le rendu de votre application ~~fait~~ côté serveur.
> c'est une proposition, à rediscuter si besoin

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Si pour une quelconque raison vous préférez ne pas utiliser le rendu côté serveur ou que vous avez besoin d'héberger statique pour votre application, vous pouvez simplement utiliser le mode applicati
vous avez besoin ~~d'héberger~~ **d'un hébergement** statique

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +### Application monopage
Je laisserai "(SPA)" à la fin du titre. C'est un acronyme très courant dans le monde du DEV et du WEB. De plus, il est expliqué dans le paragraphe qui suit.

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +## Génération statique
Génération statique (Pré-rendu)

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Va générer :
Cela générera :

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Nous ne voulons pas devoir générer manuellement l'application à chaque fois que nous mettons à jour la [documentation](https://github.com/nuxt/docs), du coup chaque modification réalisée invoque une
Nous ne voulons pas ~~devoir~~ générer manuellement l'application

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Et nous voilà avec une **application web générée sans partie serveur** :)
application web générée sans ~~partie~~ serveur **statique**

2017-09-16 05:47 UTC, forresst commented on en/guide/index.md
> +Nous pouvons aller plus loin en imaginant une application d'e-commerce créée avec `nuxt generate` et hébergée sur un CDN. Chaque fois qu'un produit est en rupture de stock ou de nouveau en stock nous
d'un serveur ou ~~un~~ **d'un** cache

2017-09-16 06:53 UTC, Haeresis commented on en/guide/index.md
> +- [Vue Router](https://github.com/vuejs/vue-router)
C'est PR à l'original. Vue-Router ça n'existe pas. C'est soit « Vue Router » pour le nom du produit, soit « vue-router » pour le nom du package.

2017-09-16 06:56 UTC, Haeresis commented on en/guide/index.md
> +Un total de seulement **57ko min+gzip** (53ko avec Vuex).
1 kilobyte = 1 kilooctet. Je vais PR l'original pour leur dire de mettre kB

2017-09-16 06:57 UTC, Haeresis commented on en/guide/index.md
> +Un total de seulement **57ko min+gzip** (53ko avec Vuex).
Et sinon 1kilobit = 1024 octets

2017-09-16 06:58 UTC, Haeresis commented on en/guide/index.md
> +Un total de seulement **57ko min+gzip** (53ko avec Vuex).
Cela dit  Vue fait la même erreur « 20kb min+gzip Runtime »

2017-09-16 06:59 UTC, forresst commented on en/guide/index.md
> +- [Vue Router](https://github.com/vuejs/vue-router)
OK

2017-09-16 07:00 UTC, forresst commented on en/guide/index.md
> +Un total de seulement **57ko min+gzip** (53ko avec Vuex).
Oui je me suis peut-être un peu planté dans les conversions 😄

2017-09-16 07:22 UTC, Haeresis commented on en/guide/index.md
> +Un total de seulement **57ko min+gzip** (53ko avec Vuex).
J'ai aussi PR l'original car pour moi c'est pas « with » mais c'est « without ». Comment quelque chose avec plus de code deviendrait moins lourd !

2017-09-16 07:22 UTC, Haeresis commented on en/guide/index.md
> +Sous le capot, nous utilisons [webpack](https://github.com/webpack/webpack) avec [vue-loader](https://github.com/vuejs/vue-loader) et [babel-loader](https://github.com/babel/babel-loader) pour empaqu
Non. J'ai déjà PR l'original
Source: https://webpack.github.io/docs/

2017-09-16 07:28 UTC, forresst commented on en/guide/index.md
> +Sous le capot, nous utilisons [webpack](https://github.com/webpack/webpack) avec [vue-loader](https://github.com/vuejs/vue-loader) et [babel-loader](https://github.com/babel/babel-loader) pour empaqu
ok

2017-09-16 07:32 UTC, Haeresis commented on en/guide/index.md
> +Un total de seulement **57ko min+gzip** (53ko avec Vuex).
Et au final j'ai aussi PR Vue pour qu'il rectifie chez eux

2017-09-16 07:39 UTC, Haeresis commented
Merci @forresst ! C'est dans la boîte !

2017-09-16 08:18 UTC, forresst approved these changes

2017-09-16 09:59 UTC, rspt approved these changes

2017-09-16 10:06 UTC, merged