Relecture de `contribution-guide.md`
vuejs-fr/nuxt pull request #7
Opened 2017-09-15 08:02 UTC by Haeresis

Je m'attaque a celle là !

2017-09-15 12:12 UTC, rspt approved these changes

2017-09-15 14:08 UTC, Kocal approved these changes

2017-09-16 06:04 UTC, forresst requested changes
Une remarque à rediscuter si besoin

2017-09-16 06:04 UTC, forresst commented on en/guide/contribution-guide.md
> +## Propositions de fusion
Je laisserai "Pull Requests"

2017-09-16 07:46 UTC, Haeresis commented on en/guide/contribution-guide.md
> +## Propositions de fusion
Je vérifie juste que j'ai bien précisé dans le corp du texte.

2017-09-16 07:52 UTC, Haeresis commented on en/guide/contribution-guide.md
> +## Propositions de fusion
Oui, comme pour SPA, c'est précisé à la ligne juste dessous.

Dans Git le fait de merger deux branche s'appelle une « fusion » en français.
Source : https://git-scm.com/book/fr/v1/Les-branches-avec-Git-Brancher-et-fusionner%C2%A0%3A-les-bases

L'onglet « Pull Requests » propre à GitHub permet, avant fusion, de proposer la fusion afin de permettre aux autres d'accepter ou de refuser la fusion. Cela me semble une traduction appropriée. Je l'ai pour ma part adoptée : 
— https://blog.lesieur.name/comprendre-et-utiliser-git-avec-vos-projets/

Si tu as une traduction plus élégante je veux bien prendre, mais je ne souhaite pas conserver un titre anglais pour quelque chose que l'on peut traduire facilement.

Qu'en pense tu ? Qu'en pense les autres ?

2017-09-16 08:19 UTC, forresst commented on en/guide/contribution-guide.md
> +## Propositions de fusion
Tu m'as convaincu, ça me va !

2017-09-16 08:19 UTC, forresst approved these changes

2017-09-16 08:43 UTC, merged