Relecture de `installation.md`
vuejs-fr/nuxt pull request #8
Opened 2017-09-15 10:52 UTC by Haeresis

Relecture de la page d'arrivée !

2017-09-15 12:19 UTC, rspt requested changes

2017-09-15 12:19 UTC, rspt commented on en/guide/installation.md
> +Pour en savoir plus sur la structure des dossiers du projet consultez [la documentation de l'architecture des dossiers](/guide/directory-structure).
"du projet, consultez"

2017-09-15 12:19 UTC, rspt commented on en/guide/installation.md
> +Pour en savoir plus sur la structure des dossier du projet consultez [la documentation de l'architecture des dossiers](/guide/directory-structure).
"des dossiers du projet, consultez"

2017-09-15 12:26 UTC, Haeresis commented
Merci pour tes retours @rspt  ! C'est tout bon.

2017-09-15 14:40 UTC, Kocal approved these changes

2017-09-16 06:17 UTC, forresst requested changes
Une petite faute et pis c'est tout !

2017-09-16 06:17 UTC, forresst commented on en/guide/installation.md
> +Pour en savoir plus sur la structure des dossier du projet, consultez [la documentation de l'architecture des dossiers](/guide/directory-structure).
la structure des dossiers du projet
> dossier au pluriel

2017-09-16 07:45 UTC, Haeresis commented
Merci @forresst ! Si c'est bon pour toi et @rspt, je merge des que vous avez appoved.

2017-09-16 08:20 UTC, forresst approved these changes

2017-09-16 10:03 UTC, rspt approved these changes

2017-09-16 10:06 UTC, merged