Relecture de `directory-structure.md`
vuejs-fr/nuxt pull request #9
Opened 2017-09-15 12:16 UTC by Haeresis

C'est parti

2017-09-15 14:48 UTC, Kocal requested changes

2017-09-15 14:48 UTC, Kocal commented on en/guide/directory-structure.md
> +Le répertoire `components` contient vos composants Vue.js. Nuxt.js surcharge pas la méthode `data` sur ces composants.
> Nuxt.js ne surcharge pas

Un peu de finesse voyons :tongue:

2017-09-15 14:48 UTC, Kocal commented on en/guide/directory-structure.md
> +Le répertoire `plugins` contient les plugins JavaScript que vous désirez exécuter avant d'instancier la racine de l'application Vue.js.
> avant d'instancier l'application Vue.js racine

2017-09-15 14:55 UTC, Haeresis commented on en/guide/directory-structure.md
> +Le répertoire `components` contient vos composants Vue.js. Nuxt.js surcharge pas la méthode `data` sur ces composants.
houga waga ! hu hu !

2017-09-15 14:57 UTC, Haeresis commented
Merci @Kocal. C'est dans la boîte !

2017-09-15 15:44 UTC, Kocal approved these changes

2017-09-16 06:35 UTC, forresst requested changes
Quelques erreurs, remarques et une question pour le genre du mot "store"

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +description: La structures par défaut d'une application Nuxt.js est destinée à fournir un excellent point de départ pour les petites et grandes applications. Bien sûr, vous êtes libre d'organiser vot
La structure par défaut
> enlever le "s" à structure

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +> La structures par défaut d'une application Nuxt.js est destinée à fournir un excellent point de départ pour les petites et grandes applications. Bien sûr, vous êtes libre d'organiser votre applicat
La structure par défaut
> enlever le "s" à structure

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +Le répertoire `assets` contient vos ressources non-compilés comme par ex. vos Less, Sass, ou JavaScript.
comme par ~~ex.~~ **exemple** vos ~~Less~~ **LESS**, ~~Sass,~~ **SASS** ou JavaScript.

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +### Le répertoire des présentations
"des mises en pages" me parait plus opportun

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +[Consultez la documentation à propos des middleware](/guide/routing#middleware)
à propos des middlewares
> middleware au pluriel

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +[Consultez la documentation à propos des plugins](/guide/plugins)
Consultez la documentation à propos **de l'intégration** des plugins

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +[Consultez la documentation à propos des fichiers statiques](/guide/assets#static)
Consultez la documentation à propos **de l'intégration** des fichiers statiques

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +Le répertoire `store` contient vos fichiers [de store Vuex](https://vuex.vuejs.org/fr/). Les stores Vuex sont implémentés de manière optionnelle dans le framework Nuxt.js. La création d'un fichier `i
optionnelle 
> La question est : "store" est de quel genre ? Si les stores sont masculin alors c'est "optionnels", si les stores sont féminins alors c'est "optionnelles".

2017-09-16 06:35 UTC, forresst commented on en/guide/directory-structure.md
> +<p class="Alert Alert--nuxt-green"><b>Info :</b> À l'intérieur de vos templates `vue`, si vous avez besoin de faire référence à vos répertoires `assets` ou `static`, utilisez par ex. `~assets/your_im
`~assets/your_image.png`
> il faut remplacer "your_image" par "votre_image"

`~static/your_image.png`.
> il faut remplacer "your_image" par "votre_image"

2017-09-16 08:29 UTC, Haeresis commented on en/guide/directory-structure.md
> +### Le répertoire des présentations
erreur de ma part, merci

2017-09-16 08:30 UTC, Haeresis commented on en/guide/directory-structure.md
> +Le répertoire `assets` contient vos ressources non-compilés comme par ex. vos Less, Sass, ou JavaScript.
Less et Sass s'écrivent ainsi selon les documentations officielles :
— Source: http://sass-lang.com/ 
— Source: http://lesscss.org/

J'ai déjà PR les originals

2017-09-16 08:41 UTC, Haeresis commented on en/guide/directory-structure.md
> +Le répertoire `store` contient vos fichiers [de store Vuex](https://vuex.vuejs.org/fr/). Les stores Vuex sont implémentés de manière optionnelle dans le framework Nuxt.js. La création d'un fichier `i
Il me semble que c'est « la manière » qui est optionnelle dans ce contexte. Si tu souhaites revoir la phrase je te laisse proposer :)

2017-09-16 08:41 UTC, Haeresis commented
C'est dans la boîte. Merci @forresst !

2017-09-16 10:08 UTC, rspt requested changes

2017-09-16 10:08 UTC, rspt commented on en/guide/directory-structure.md
> +Le répertoire `assets` contient vos ressources non-compilés comme par exemple vos Less, Sass, ou JavaScript.
"Le répertoire `assets` contient vos ressources non compilées; par exemple vos fichiers Less, Sass, ou JavaScript."

---

- Correction de "non compilées"
- Le "comme par exemple" est un pléonasme
- J'ajouterais aussi un point-virgule et le mot fichiers (ou un équivalent) pour donner un peu plus de rythme

2017-09-16 10:08 UTC, rspt commented on en/guide/directory-structure.md
> +<p class="Alert Alert--nuxt-green"><b>Info :</b> À l'intérieur de vos templates `vue`, si vous avez besoin de faire référence à vos répertoires `assets` ou `static`, utilisez par ex. `~assets/votre_i
Je mettrais une minuscule après les deux points; soit "à l'intérieur".

2017-09-16 10:13 UTC, Haeresis commented on en/guide/directory-structure.md
> +Le répertoire `assets` contient vos ressources non-compilés comme par exemple vos Less, Sass, ou JavaScript.
Je vais mettre « tels que » pour coller à l'original

2017-09-16 10:15 UTC, Haeresis commented
Merci @rspt pour ta review. J'ai mis « contient vos ressources non compilées tels que vos fichiers Less, Sass ou JavaScript. » suite à tes remarques. Bon pour toi ?

2017-09-16 10:18 UTC, rspt commented
> Merci @rspt pour ta review. J'ai mis « contient vos ressources non compilées tels que vos fichiers Less, Sass ou JavaScript. » suite à tes remarques. Bon pour toi ?

Parfait! Encore mieux 👍

2017-09-16 10:18 UTC, rspt approved these changes

2017-09-16 10:19 UTC, Haeresis commented
Et pour toi @forresst ?

2017-09-16 12:01 UTC, forresst commented on en/guide/directory-structure.md
> +Le répertoire `store` contient vos fichiers [de store Vuex](https://vuex.vuejs.org/fr/). Les stores Vuex sont implémentés de manière optionnelle dans le framework Nuxt.js. La création d'un fichier `i
Bien vu. Tu as raison

2017-09-16 12:03 UTC, forresst approved these changes

2017-09-16 12:12 UTC, merged